//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMCH
    {
        public string MSCH { get; set; }
        public string TENCH { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
    }
}
