//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.PostUsers = new HashSet<PostUser>();
        }
    
        public int Id { get; set; }
        public int PostId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> IdAlbum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostUser> PostUsers { get; set; }
        public virtual PostUser PostUser { get; set; }
        public virtual Ablum Ablum { get; set; }
    }
}
